from fpdf import FPDF
import os

class QAPDF(FPDF):
    def header(self):
        # ---- Professional Corporate Header ----
        logo_path = "logo.png"
        if os.path.exists(logo_path):
            self.image(logo_path, x=10, y=8, w=20)
        
        self.set_y(10)
        self.set_font("Helvetica", 'B', 20)
        self.set_text_color(26, 35, 126)   # Deep indigo
        self.cell(0, 8, text="Bapuji Textile Industries", align='R', new_x="LMARGIN", new_y="NEXT")
        
        self.set_font("Helvetica", size=9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, text="Davanagere, Karnataka - 577002 | Weaving Quality Since 1990", align='R', new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 5, text="Phone: +91-8192-XXXXXX | Email: management@bapujitextile.com", align='R', new_x="LMARGIN", new_y="NEXT")
        
        self.set_y(32)
        self.set_draw_color(26, 35, 126)
        self.set_line_width(0.8)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_line_width(0.2)
        self.set_y(36)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, text=f"Page {self.page_no()}", align='C', new_x="LMARGIN")
        self.set_y(-15)
        self.cell(0, 10, text="CONFIDENTIAL - Internal Preparation Use Only", align='L', new_x="LMARGIN")
        self.set_y(-15)
        self.cell(0, 10, text="Generated by AI Analytics Dashboard", align='R', new_x="LMARGIN", new_y="NEXT")

def create_qa_pdf():
    pdf = QAPDF()
    pdf.add_page()
    
    # ---- Report Title Block ----
    pdf.set_y(40)
    pdf.set_font("Helvetica", 'B', 22)
    pdf.set_text_color(26, 35, 126)
    pdf.cell(0, 12, text="EXECUTIVE Q&A PREPARATION GUIDE", align='C', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, text="Subject: Anticipated Board Questions & System Architecture", align='C', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    questions = [
        {
            "q": "1. How does the AI actually predict the next month's sales?",
            "a": "The system uses a Machine Learning model called Polynomial Regression. It analyzes historical trends and curves in our past data to mathematically forecast where the sales are heading next month."
        },
        {
            "q": "2. Where does the AI get the 'Reasons for Downfall/Growth'?",
            "a": "The engine looks at Growth Momentum (month-over-month changes) and Volatility (fluctuations). If it sees momentum dropping while volatility is high, it flags a structural risk."
        },
        {
            "q": "3. How accurate is this prediction?",
            "a": "In the PDF's Executive Summary, you'll see a metric called 'Model Accuracy (R-squared)'. The closer that number is to 1.0, the more confident we can be in the prediction."
        },
        {
            "q": "4. What happens if we want to look at a completely different dataset?",
            "a": "The dashboard is dynamic. Just click 'Upload Custom CSV', upload the new data, and the AI will instantly retrain itself and generate a brand-new PDF report."
        },
        {
            "q": "5. How is the PDF generated? Did you just use a template?",
            "a": "No, the PDF is generated programmatically from scratch in real-time. Every time you click the download button, the code dynamically draws the letterhead and builds the tables based on the data."
        },
        {
            "q": "6. Is this data secure? Where is it being stored?",
            "a": "The system runs completely locally on our infrastructure. The data is never sent to external third-party servers. It is highly secure and isolated."
        },
        {
            "q": "7. How can we improve the accuracy even further?",
            "a": "If we start uploading richer datasets that include external factors (like marketing spend or seasonal weather), we can upgrade the AI to an XGBoost model for near-perfect accuracy."
        },
        {
            "q": "8. Why is the prediction lower/higher than I expected?",
            "a": "The AI is purely objective and data-driven. It mathematically calculates the momentum of the last few months. If sales have been trending slightly downward, it will project that downward curve."
        }
    ]

    for item in questions:
        # Question
        pdf.set_font("Helvetica", 'B', 12)
        pdf.set_text_color(26, 35, 126) # Indigo
        q_safe = item["q"].encode('latin-1', 'ignore').decode('latin-1').strip()
        pdf.multi_cell(0, 7, text=q_safe, new_x="LMARGIN", new_y="NEXT")
        
        # Answer
        pdf.set_font("Helvetica", '', 11)
        pdf.set_text_color(50, 50, 50)
        a_safe = item["a"].encode('latin-1', 'ignore').decode('latin-1').strip()
        
        # Indent the answer using set_x
        pdf.set_x(15)
        pdf.multi_cell(185, 6, text="Answer: " + a_safe, new_x="LMARGIN", new_y="NEXT")
        pdf.set_x(10) # Reset x for next question
        pdf.ln(4)

    pdf.output("Bapuji_QA_Guide_Fixed.pdf")

if __name__ == "__main__":
    create_qa_pdf()
